import type { AlgoId } from "./algos";

export type Lang = "ts" | "rust" | "java";

export interface Snippet {
  ts: string[];
  rust: string[];
  java: string[];
}

// Lines are 0-indexed. Keep structure aligned across langs so activeLine works for all three.
export const CODE: Partial<Record<AlgoId, Snippet>> = {
  "bubble-sort": {
    ts: [
      "function bubbleSort(arr: number[]): number[] {",
      "  const n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j+1]] = [arr[j+1], arr[j]];",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}",
    ],
    rust: [
      "fn bubble_sort(arr: &mut Vec<i32>) {",
      "  let n = arr.len();",
      "  for i in 0..n - 1 {",
      "    for j in 0..n - i - 1 {",
      "      if arr[j] > arr[j + 1] {",
      "        arr.swap(j, j + 1);",
      "      }",
      "    }",
      "  }",
      "  // sorted!",
      "}",
    ],
    java: [
      "void bubbleSort(int[] arr) {",
      "  int n = arr.length;",
      "  for (int i = 0; i < n - 1; i++) {",
      "    for (int j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        int t=arr[j]; arr[j]=arr[j+1]; arr[j+1]=t;",
      "      }",
      "    }",
      "  }",
      "  // sorted!",
      "}",
    ],
  },

  "selection-sort": {
    ts: [
      "function selectionSort(arr: number[]): number[] {",
      "  const n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let minIdx = i;",
      "    for (let j = i + 1; j < n; j++) {",
      "      if (arr[j] < arr[minIdx]) minIdx = j;",
      "    }",
      "    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];",
      "  }",
      "  return arr;",
      "}",
    ],
    rust: [
      "fn selection_sort(arr: &mut Vec<i32>) {",
      "  let n = arr.len();",
      "  for i in 0..n - 1 {",
      "    let mut min_idx = i;",
      "    for j in (i + 1)..n {",
      "      if arr[j] < arr[min_idx] { min_idx = j; }",
      "    }",
      "    arr.swap(i, min_idx);",
      "  }",
      "  // sorted!",
      "}",
    ],
    java: [
      "void selectionSort(int[] arr) {",
      "  int n = arr.length;",
      "  for (int i = 0; i < n - 1; i++) {",
      "    int minIdx = i;",
      "    for (int j = i + 1; j < n; j++) {",
      "      if (arr[j] < arr[minIdx]) minIdx = j;",
      "    }",
      "    int t=arr[i]; arr[i]=arr[minIdx]; arr[minIdx]=t;",
      "  }",
      "  // sorted!",
      "}",
    ],
  },

  "insertion-sort": {
    ts: [
      "function insertionSort(arr: number[]): number[] {",
      "  for (let i = 1; i < arr.length; i++) {",
      "    let j = i;",
      "    while (j > 0 && arr[j - 1] > arr[j]) {",
      "      [arr[j-1], arr[j]] = [arr[j], arr[j-1]];",
      "      j--;",
      "    }",
      "  }",
      "  return arr;",
      "}",
    ],
    rust: [
      "fn insertion_sort(arr: &mut Vec<i32>) {",
      "  for i in 1..arr.len() {",
      "    let mut j = i;",
      "    while j > 0 && arr[j - 1] > arr[j] {",
      "      arr.swap(j - 1, j);",
      "      j -= 1;",
      "    }",
      "  }",
      "  // sorted!",
      "}",
    ],
    java: [
      "void insertionSort(int[] arr) {",
      "  for (int i = 1; i < arr.length; i++) {",
      "    int j = i;",
      "    while (j > 0 && arr[j - 1] > arr[j]) {",
      "      int t=arr[j-1]; arr[j-1]=arr[j]; arr[j]=t;",
      "      j--;",
      "    }",
      "  }",
      "  // sorted!",
      "}",
    ],
  },

  "merge-sort": {
    ts: [
      "function mergeSort(arr: number[], l = 0, r = arr.length-1) {",
      "  if (l >= r) return;",
      "  const m = (l + r) >> 1;",
      "  mergeSort(arr, l, m);",
      "  mergeSort(arr, m + 1, r);",
      "  const L = arr.slice(l, m+1), R = arr.slice(m+1, r+1);",
      "  let i = 0, j = 0, k = l;",
      "  while (i < L.length && j < R.length) {",
      "    if (L[i] <= R[j]) arr[k++] = L[i++];",
      "    else arr[k++] = R[j++];",
      "  }",
      "  while (i < L.length) arr[k++] = L[i++];",
      "  while (j < R.length) arr[k++] = R[j++];",
      "}",
    ],
    rust: [
      "fn merge_sort(arr: &mut Vec<i32>, l: usize, r: usize) {",
      "  if l >= r { return; }",
      "  let m = l + (r - l) / 2;",
      "  merge_sort(arr, l, m);",
      "  merge_sort(arr, m + 1, r);",
      "  let (lv, rv) = (arr[l..=m].to_vec(), arr[m+1..=r].to_vec());",
      "  let (mut i, mut j, mut k) = (0, 0, l);",
      "  while i < lv.len() && j < rv.len() {",
      "    if lv[i] <= rv[j] { arr[k] = lv[i]; i+=1; }",
      "    else { arr[k] = rv[j]; j+=1; } k+=1;",
      "  }",
      "  while i < lv.len() { arr[k] = lv[i]; i+=1; k+=1; }",
      "  while j < rv.len() { arr[k] = rv[j]; j+=1; k+=1; }",
      "}",
    ],
    java: [
      "void mergeSort(int[] arr, int l, int r) {",
      "  if (l >= r) return;",
      "  int m = (l + r) / 2;",
      "  mergeSort(arr, l, m);",
      "  mergeSort(arr, m + 1, r);",
      "  int[] L=Arrays.copyOfRange(arr,l,m+1), R=Arrays.copyOfRange(arr,m+1,r+1);",
      "  int i=0, j=0, k=l;",
      "  while (i < L.length && j < R.length) {",
      "    if (L[i] <= R[j]) arr[k++] = L[i++];",
      "    else arr[k++] = R[j++];",
      "  }",
      "  while (i < L.length) arr[k++] = L[i++];",
      "  while (j < R.length) arr[k++] = R[j++];",
      "}",
    ],
  },

  "quick-sort": {
    ts: [
      "function quickSort(arr: number[], lo = 0, hi = arr.length-1) {",
      "  if (lo >= hi) return;",
      "  let i = lo - 1;",
      "  const pivot = arr[hi];",
      "  for (let j = lo; j < hi; j++) {",
      "    if (arr[j] <= pivot) {",
      "      i++;",
      "      [arr[i], arr[j]] = [arr[j], arr[i]];",
      "    }",
      "  }",
      "  [arr[i+1], arr[hi]] = [arr[hi], arr[i+1]];",
      "  const pi = i + 1;",
      "  quickSort(arr, lo, pi - 1);",
      "  quickSort(arr, pi + 1, hi);",
      "}",
    ],
    rust: [
      "fn quick_sort(arr: &mut [i32]) {",
      "  if arr.len() <= 1 { return; }",
      "  let mut i = 0usize;",
      "  let pivot = *arr.last().unwrap();",
      "  for j in 0..arr.len() - 1 {",
      "    if arr[j] <= pivot {",
      "      arr.swap(i, j);",
      "      i += 1;",
      "    }",
      "  }",
      "  arr.swap(i, arr.len() - 1);",
      "  let pi = i;",
      "  quick_sort(&mut arr[..pi]);",
      "  quick_sort(&mut arr[pi+1..]);",
      "}",
    ],
    java: [
      "void quickSort(int[] arr, int lo, int hi) {",
      "  if (lo >= hi) return;",
      "  int i = lo - 1;",
      "  int pivot = arr[hi];",
      "  for (int j = lo; j < hi; j++) {",
      "    if (arr[j] <= pivot) {",
      "      i++;",
      "      int t=arr[i]; arr[i]=arr[j]; arr[j]=t;",
      "    }",
      "  }",
      "  int t=arr[i+1]; arr[i+1]=arr[hi]; arr[hi]=t;",
      "  int pi = i + 1;",
      "  quickSort(arr, lo, pi - 1);",
      "  quickSort(arr, pi + 1, hi);",
      "}",
    ],
  },

  bfs: {
    ts: [
      "function bfs(grid, start, end) {",
      "  const queue = [start];",
      "  const visited = new Set([key(start)]);",
      "  const parent = new Map();",
      "",
      "  while (queue.length > 0) {",
      "    const curr = queue.shift();",
      "    if (equals(curr, end)) return buildPath(parent, end);",
      "",
      "    for (const next of neighbors(grid, curr)) {",
      "      if (!visited.has(key(next))) {",
      "        visited.add(key(next));",
      "        parent.set(key(next), curr);",
      "        queue.push(next);",
      "      }",
      "    }",
      "  }",
      "  return null; // no path",
      "}",
    ],
    rust: [
      "fn bfs(grid: &Grid, start: Pos, end: Pos) -> Option<Vec<Pos>> {",
      "  let mut queue = VecDeque::from([start]);",
      "  let mut visited = HashSet::from([start]);",
      "  let mut parent: HashMap<Pos, Pos> = HashMap::new();",
      "",
      "  while let Some(curr) = queue.pop_front() {",
      "    // curr dequeued",
      "    if curr == end { return Some(build_path(&parent, end)); }",
      "",
      "    for next in neighbors(grid, curr) {",
      "      if !visited.contains(&next) {",
      "        visited.insert(next);",
      "        parent.insert(next, curr);",
      "        queue.push_back(next);",
      "      }",
      "    }",
      "  }",
      "  None // no path",
      "}",
    ],
    java: [
      "List<int[]> bfs(int[][] grid, int[] start, int[] end) {",
      "  Queue<int[]> queue = new LinkedList<>(); queue.add(start);",
      "  Set<String> visited = new HashSet<>(); visited.add(key(start));",
      "  Map<String, int[]> parent = new HashMap<>();",
      "",
      "  while (!queue.isEmpty()) {",
      "    int[] curr = queue.poll();",
      "    if (Arrays.equals(curr, end)) return buildPath(parent, end);",
      "",
      "    for (int[] next : neighbors(grid, curr)) {",
      "      if (!visited.contains(key(next))) {",
      "        visited.add(key(next));",
      "        parent.put(key(next), curr);",
      "        queue.add(next);",
      "      }",
      "    }",
      "  }",
      "  return null; // no path",
      "}",
    ],
  },

  dfs: {
    ts: [
      "function dfs(grid, start, end) {",
      "  const stack = [start];",
      "  const visited = new Set([key(start)]);",
      "  const parent = new Map();",
      "",
      "  while (stack.length > 0) {",
      "    const curr = stack.pop();",
      "    if (equals(curr, end)) return buildPath(parent, end);",
      "",
      "    for (const next of neighbors(grid, curr)) {",
      "      if (!visited.has(key(next))) {",
      "        visited.add(key(next));",
      "        parent.set(key(next), curr);",
      "        stack.push(next);",
      "      }",
      "    }",
      "  }",
      "  return null; // no path",
      "}",
    ],
    rust: [
      "fn dfs(grid: &Grid, start: Pos, end: Pos) -> Option<Vec<Pos>> {",
      "  let mut stack = vec![start];",
      "  let mut visited = HashSet::from([start]);",
      "  let mut parent: HashMap<Pos, Pos> = HashMap::new();",
      "",
      "  while let Some(curr) = stack.pop() {",
      "    // curr popped",
      "    if curr == end { return Some(build_path(&parent, end)); }",
      "",
      "    for next in neighbors(grid, curr) {",
      "      if !visited.contains(&next) {",
      "        visited.insert(next);",
      "        parent.insert(next, curr);",
      "        stack.push(next);",
      "      }",
      "    }",
      "  }",
      "  None // no path",
      "}",
    ],
    java: [
      "List<int[]> dfs(int[][] grid, int[] start, int[] end) {",
      "  Deque<int[]> stack = new ArrayDeque<>(); stack.push(start);",
      "  Set<String> visited = new HashSet<>(); visited.add(key(start));",
      "  Map<String, int[]> parent = new HashMap<>();",
      "",
      "  while (!stack.isEmpty()) {",
      "    int[] curr = stack.pop();",
      "    if (Arrays.equals(curr, end)) return buildPath(parent, end);",
      "",
      "    for (int[] next : neighbors(grid, curr)) {",
      "      if (!visited.contains(key(next))) {",
      "        visited.add(key(next));",
      "        parent.put(key(next), curr);",
      "        stack.push(next);",
      "      }",
      "    }",
      "  }",
      "  return null; // no path",
      "}",
    ],
  },

  dijkstra: {
    ts: [
      "function dijkstra(graph, src) {",
      "  const dist = {}; // dist[v] = best distance",
      "  const pq = new MinPQ(); pq.push(0, src);",
      "  dist[src] = 0;",
      "  while (!pq.isEmpty()) {",
      "    const [d, u] = pq.pop();",
      "    if (d > dist[u]) continue; // stale entry",
      "    if (u === end) return dist; // reached goal",
      "    for (const [v, w] of graph[u]) {",
      "      // relax edge u→v",
      "      const nd = dist[u] + w;",
      "      if (nd < (dist[v] ?? Infinity)) {",
      "        dist[v] = nd;",
      "        pq.push(nd, v);",
      "      }",
      "    }",
      "  }",
      "  return dist; // no path",
      "}",
    ],
    rust: [
      "fn dijkstra(graph: &Vec<Vec<(usize,u32)>>, src: usize) -> Vec<u32> {",
      "  let mut dist = vec![u32::MAX; graph.len()];",
      "  let mut pq = BinaryHeap::new();",
      "  dist[src] = 0; pq.push(Reverse((0, src)));",
      "  while let Some(Reverse((d, u))) = pq.pop() {",
      "    if d > dist[u] { continue; }",
      "    if u == end { return dist; }",
      "    for &(v, w) in &graph[u] {",
      "      // relax edge",
      "      let nd = dist[u] + w;",
      "      if nd < dist[v] {",
      "        dist[v] = nd;",
      "        pq.push(Reverse((nd, v)));",
      "      }",
      "    }",
      "  }",
      "  dist",
      "}",
    ],
    java: [
      "int[] dijkstra(List<int[]>[] graph, int src) {",
      "  int[] dist = new int[n]; Arrays.fill(dist, Integer.MAX_VALUE);",
      "  PriorityQueue<int[]> pq = new PriorityQueue<>(Comparator.comparingInt(a->a[0]));",
      "  dist[src] = 0; pq.offer(new int[]{0, src});",
      "  while (!pq.isEmpty()) {",
      "    int[] curr = pq.poll();",
      "    if (curr[0] > dist[curr[1]]) continue;",
      "    if (curr[1] == end) return dist;",
      "    for (int[] e : graph[curr[1]]) {",
      "      // relax edge",
      "      int nd = dist[curr[1]] + e[1];",
      "      if (nd < dist[e[0]]) {",
      "        dist[e[0]] = nd;",
      "        pq.offer(new int[]{nd, e[0]});",
      "      }",
      "    }",
      "  }",
      "  return dist;",
      "}",
    ],
  },

  astar: {
    ts: [
      "function aStar(grid, start, end) {",
      "  const g = {}; g[key(start)] = 0;",
      "  const open = new MinPQ(); open.push(h(start), start);",
      "  const parent = {};",
      "  while (!open.isEmpty()) {",
      "    const curr = open.pop(); // f = g + h",
      "    if (equals(curr, end)) return buildPath(parent, end);",
      "    for (const next of neighbors(grid, curr)) {",
      "      const tg = g[key(curr)] + cost(curr, next);",
      "      if (tg < (g[key(next)] ?? Infinity)) {",
      "        g[key(next)] = tg;",
      "        parent[key(next)] = curr;",
      "        open.push(tg + h(next), next);",
      "      }",
      "    }",
      "  }",
      "  return null; // no path",
      "}",
    ],
    rust: [
      "fn astar(grid: &Grid, start: Pos, end: Pos) -> Option<Vec<Pos>> {",
      "  let mut g: HashMap<Pos,u32> = HashMap::from([(start, 0)]);",
      "  let mut open = BinaryHeap::new();",
      "  open.push(Reverse((h(start,end), start)));",
      "  let mut parent: HashMap<Pos, Pos> = HashMap::new();",
      "  while let Some(Reverse((_, curr))) = open.pop() {",
      "    if curr == end { return Some(build_path(&parent, end)); }",
      "    for next in neighbors(grid, curr) {",
      "      let tg = g[&curr] + cost(curr, next);",
      "      if tg < *g.get(&next).unwrap_or(&u32::MAX) {",
      "        g.insert(next, tg);",
      "        parent.insert(next, curr);",
      "        open.push(Reverse((tg + h(next, end), next)));",
      "      }",
      "    }",
      "  }",
      "  None",
      "}",
    ],
    java: [
      "List<int[]> aStar(int[][] grid, int[] start, int[] end) {",
      "  Map<String,Integer> g = new HashMap<>(); g.put(key(start), 0);",
      "  PriorityQueue<int[]> open = new PriorityQueue<>(Comparator.comparingInt(a->a[0]));",
      "  open.offer(new int[]{h(start,end), start[0], start[1]});",
      "  Map<String,int[]> parent = new HashMap<>();",
      "  while (!open.isEmpty()) {",
      "    int[] curr = open.poll();",
      "    if (Arrays.equals(pos(curr), end)) return buildPath(parent, end);",
      "    for (int[] next : neighbors(grid, pos(curr))) {",
      "      int tg = g.get(key(pos(curr))) + cost(pos(curr), next);",
      "      if (tg < g.getOrDefault(key(next), Integer.MAX_VALUE)) {",
      "        g.put(key(next), tg);",
      "        parent.put(key(next), pos(curr));",
      "        open.offer(new int[]{tg + h(next, end), next[0], next[1]});",
      "      }",
      "    }",
      "  }",
      "  return null;",
      "}",
    ],
  },

  kruskal: {
    ts: [
      "edges.sort((a, b) => a.weight - b.weight);",
      "const uf = new UnionFind(n);",
      "const mst: Edge[] = [];",
      "for (const edge of edges) {",
      "  const { from, to, weight } = edge;",
      "  if (!uf.connected(from, to)) {",
      "    uf.union(from, to);",
      "    mst.push(edge);",
      "    if (mst.length === n - 1) break;",
      "  }",
      "}",
    ],
    rust: [
      "edges.sort_by_key(|e| e.weight);",
      "let mut uf = UnionFind::new(n);",
      "let mut mst: Vec<&Edge> = vec![];",
      "for edge in &edges {",
      "  let (u, v) = (edge.from, edge.to);",
      "  if !uf.connected(u, v) {",
      "    uf.union(u, v);",
      "    mst.push(edge);",
      "    if mst.len() == n - 1 { break; }",
      "  }",
      "}",
    ],
    java: [
      "Arrays.sort(edges, Comparator.comparingInt(e -> e.weight));",
      "UnionFind uf = new UnionFind(n);",
      "List<Edge> mst = new ArrayList<>();",
      "for (Edge edge : edges) {",
      "  int u = edge.from, v = edge.to;",
      "  if (!uf.connected(u, v)) {",
      "    uf.union(u, v);",
      "    mst.add(edge);",
      "    if (mst.size() == n - 1) break;",
      "  }",
      "}",
    ],
  },

  prim: {
    ts: [
      "const inMST = new Set([0]);",
      "const pq = new MinPQ(); addEdges(0);",
      "const mst: Edge[] = [];",
      "",
      "while (!pq.isEmpty() && inMST.size < n) {",
      "  const edge = pq.pop();",
      "  if (inMST.has(edge.to)) continue;",
      "  inMST.add(edge.to); mst.push(edge);",
      "  for (const e of adj[edge.to]) {",
      "    if (!inMST.has(e.to)) pq.push(e);",
      "  }",
      "}",
      "// mst is complete",
    ],
    rust: [
      "let mut in_mst = HashSet::from([0usize]);",
      "let mut pq = BinaryHeap::new(); add_edges(0, &mut pq);",
      "let mut mst = vec![];",
      "",
      "while let Some(edge) = pq.pop() {",
      "  if in_mst.contains(&edge.to) { continue; }",
      "  in_mst.insert(edge.to); mst.push(edge.clone());",
      "  for e in &adj[edge.to] {",
      "    if !in_mst.contains(&e.to) { pq.push(e.clone()); }",
      "  }",
      "}",
      "// mst complete",
    ],
    java: [
      "Set<Integer> inMST = new HashSet<>(); inMST.add(0);",
      "PriorityQueue<Edge> pq = new PriorityQueue<>(Comparator.comparingInt(e->e.w)); addEdges(0, pq);",
      "List<Edge> mst = new ArrayList<>();",
      "",
      "while (!pq.isEmpty() && inMST.size() < n) {",
      "  Edge edge = pq.poll();",
      "  if (inMST.contains(edge.to)) continue;",
      "  inMST.add(edge.to); mst.add(edge);",
      "  for (Edge e : adj[edge.to]) {",
      "    if (!inMST.contains(e.to)) pq.offer(e);",
      "  }",
      "}",
      "// mst complete",
    ],
  },

  "fibonacci-dp": {
    ts: [
      "function fib(n: number): number {",
      "  const dp = [0, 1];",
      "  if (n <= 1) return dp[n];",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2];",
      "  }",
      "  return dp[n];",
      "}",
    ],
    rust: [
      "fn fib(n: usize) -> u64 {",
      "  let mut dp = vec![0u64; n + 1];",
      "  dp[1] = 1;",
      "  for i in 2..=n {",
      "    dp[i] = dp[i - 1] + dp[i - 2];",
      "  }",
      "  dp[n]",
      "}",
    ],
    java: [
      "long fib(int n) {",
      "  long[] dp = new long[n + 1];",
      "  dp[1] = 1;",
      "  for (int i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2];",
      "  }",
      "  return dp[n];",
      "}",
    ],
  },

  "knapsack-dp": {
    ts: [
      "// dp[i][w] = max value using first i items, capacity w",
      "const dp = Array(n+1).fill(0).map(() => Array(W+1).fill(0));",
      "for (let i = 1; i <= n; i++) {",
      "  const { weight: wi, value: vi } = items[i-1];",
      "  for (let w = 0; w <= W; w++) {",
      "    dp[i][w] = dp[i-1][w]; // skip item i",
      "    if (wi <= w) {",
      "      const withItem = vi + dp[i-1][w - wi];",
      "      dp[i][w] = Math.max(dp[i][w], withItem);",
      "    }",
      "  }",
      "}",
      "return dp[n][W]; // answer",
    ],
    rust: [
      "// dp[i][w] = max value first i items, capacity w",
      "let mut dp = vec![vec![0u32; W+1]; n+1];",
      "for i in 1..=n {",
      "  let (wi, vi) = items[i-1];",
      "  for w in 0..=W {",
      "    dp[i][w] = dp[i-1][w];",
      "    if wi <= w {",
      "      dp[i][w] = dp[i][w].max(vi + dp[i-1][w - wi]);",
      "    }",
      "  }",
      "}",
      "dp[n][W] // answer",
    ],
    java: [
      "// dp[i][w] = max value first i items, capacity w",
      "int[][] dp = new int[n+1][W+1];",
      "for (int i = 1; i <= n; i++) {",
      "  int wi = items[i-1][0], vi = items[i-1][1];",
      "  for (int w = 0; w <= W; w++) {",
      "    dp[i][w] = dp[i-1][w];",
      "    if (wi <= w) {",
      "      dp[i][w] = Math.max(dp[i][w], vi + dp[i-1][w - wi]);",
      "    }",
      "  }",
      "}",
      "return dp[n][W]; // answer",
    ],
  },

  "n-queens": {
    ts: [
      "function solve(board, row) {",
      "  if (row === n) { solutions.push(copy(board)); return; }",
      "  for (let col = 0; col < n; col++) {",
      "    // try placing queen at (row, col)",
      "    if (isSafe(board, row, col)) {",
      "      board[row][col] = 1;",
      "      solve(board, row + 1); // recurse",
      "      board[row][col] = 0; // backtrack",
      "    }",
      "  }",
      "  // no valid column found",
      "}",
    ],
    rust: [
      "fn solve(board: &mut Vec<Vec<u8>>, row: usize, n: usize) {",
      "  if row == n { solutions.push(board.clone()); return; }",
      "  for col in 0..n {",
      "    // try placing queen at (row, col)",
      "    if is_safe(board, row, col, n) {",
      "      board[row][col] = 1;",
      "      solve(board, row + 1, n); // recurse",
      "      board[row][col] = 0; // backtrack",
      "    }",
      "  }",
      "  // no valid column",
      "}",
    ],
    java: [
      "void solve(int[][] board, int row) {",
      "  if (row == n) { solutions.add(copy(board)); return; }",
      "  for (int col = 0; col < n; col++) {",
      "    // try placing queen at (row, col)",
      "    if (isSafe(board, row, col)) {",
      "      board[row][col] = 1;",
      "      solve(board, row + 1); // recurse",
      "      board[row][col] = 0; // backtrack",
      "    }",
      "  }",
      "  // no valid column",
      "}",
    ],
  },

  kmp: {
    ts: [
      "// Phase 1: build failure table",
      "for (let fi = 1; fi < m; fi++) {",
      "  if (pat[fi] === pat[len]) { fail[fi] = ++len; fi++; }",
      "  else if (len > 0) { len = fail[len - 1]; }",
      "  else { fail[fi] = 0; fi++; }",
      "}",
      "",
      "// Phase 2: search",
      "for (let ti = 0; ti < n; ) {",
      "  if (text[ti] === pat[pi]) { ti++; pi++; }",
      "  if (pi === m) { matches.push(ti - pi); pi = fail[pi-1]; }",
      "  else if (ti < n && text[ti] !== pat[pi]) {",
      "    if (pi > 0) pi = fail[pi - 1];",
      "    else ti++;",
      "  }",
      "}",
    ],
    rust: [
      "// Phase 1: build failure table",
      "for fi in 1..m {",
      "  if pat[fi] == pat[len] { fail[fi] = len + 1; len += 1; }",
      "  else if len > 0 { len = fail[len - 1]; continue; }",
      "  else { fail[fi] = 0; }",
      "}",
      "",
      "// Phase 2: search",
      "let (mut ti, mut pi) = (0usize, 0usize);",
      "while ti < n {",
      "  if text[ti] == pat[pi] { ti += 1; pi += 1; }",
      "  if pi == m { matches.push(ti - pi); pi = fail[pi - 1]; }",
      "  else if ti < n && text[ti] != pat[pi] {",
      "    if pi > 0 { pi = fail[pi - 1]; } else { ti += 1; }",
      "  }",
      "}",
    ],
    java: [
      "// Phase 1: build failure table",
      "for (int fi = 1; fi < m; ) {",
      "  if (pat[fi] == pat[len]) { fail[fi++] = ++len; }",
      "  else if (len > 0) { len = fail[len - 1]; }",
      "  else { fail[fi++] = 0; }",
      "}",
      "",
      "// Phase 2: search",
      "int ti = 0, pi = 0;",
      "while (ti < n) {",
      "  if (text[ti] == pat[pi]) { ti++; pi++; }",
      "  if (pi == m) { matches.add(ti - pi); pi = fail[pi - 1]; }",
      "  else if (ti < n && text[ti] != pat[pi]) {",
      "    if (pi > 0) pi = fail[pi - 1]; else ti++;",
      "  }",
      "}",
    ],
  },

  bst: {
    ts: [
      "function insert(node, val) {",
      "  if (!node) return new Node(val); // found spot",
      "  if (val < node.val) node.left = insert(node.left, val);",
      "  else node.right = insert(node.right, val);",
      "  return node;",
      "}",
      "",
      "function search(node, val) {",
      "  if (!node) return false; // not found",
      "  if (val === node.val) return true; // found!",
      "  if (val < node.val) return search(node.left, val);",
      "  return search(node.right, val);",
      "  // not found",
      "}",
    ],
    rust: [
      "fn insert(&mut self, val: i32) {",
      "  if self.root.is_none() { self.root = Some(Box::new(Node::new(val))); return; }",
      "  if val < node.val { go_left(node); }",
      "  else { go_right(node); }",
      "  // inserted",
      "}",
      "",
      "fn search(&self, val: i32) -> bool {",
      "  if node.is_none() { return false; }",
      "  if val == node.val { return true; }",
      "  if val < node.val { return search(node.left, val); }",
      "  search(node.right, val)",
      "  // not found",
      "}",
    ],
    java: [
      "TreeNode insert(TreeNode node, int val) {",
      "  if (node == null) return new TreeNode(val); // found spot",
      "  if (val < node.val) node.left = insert(node.left, val);",
      "  else node.right = insert(node.right, val);",
      "  return node;",
      "}",
      "",
      "boolean search(TreeNode node, int val) {",
      "  if (node == null) return false; // not found",
      "  if (val == node.val) return true; // found!",
      "  if (val < node.val) return search(node.left, val);",
      "  return search(node.right, val);",
      "  // unreachable",
      "}",
    ],
  },

  heap: {
    ts: [
      "function heapify(arr, n, i) {",
      "  let largest = i;",
      "  const l = 2*i+1, r = 2*i+2;",
      "  if (l < n && arr[l] > arr[largest]) largest = l;",
      "  if (r < n && arr[r] > arr[largest]) largest = r;",
      "  if (largest !== i) { swap(arr, i, largest); heapify(arr, n, largest); }",
      "  // heap property restored",
      "}",
      "function insert(heap, val) {",
      "  heap.push(val); let i = heap.length - 1;",
      "  while (i > 0 && heap[parent(i)] < heap[i]) {",
      "    swap(heap, i, parent(i)); i = parent(i);",
      "  }",
      "}",
      "function extractMax(heap) {",
      "  swap(heap, 0, heap.length - 1); heap.pop();",
      "  heapify(heap, heap.length, 0);",
      "  return max; // removed",
      "}",
    ],
    rust: [
      "fn heapify(arr: &mut Vec<i32>, n: usize, i: usize) {",
      "  let (mut largest, l, r) = (i, 2*i+1, 2*i+2);",
      "  if l < n && arr[l] > arr[largest] { largest = l; }",
      "  if r < n && arr[r] > arr[largest] { largest = r; }",
      "  if largest != i { arr.swap(i, largest); heapify(arr, n, largest); }",
      "  // heap property restored",
      "}",
      "fn insert(heap: &mut Vec<i32>, val: i32) {",
      "  heap.push(val); let mut i = heap.len() - 1;",
      "  while i > 0 && heap[(i-1)/2] < heap[i] {",
      "    heap.swap(i, (i-1)/2); i = (i-1)/2;",
      "  }",
      "}",
      "fn extract_max(heap: &mut Vec<i32>) -> i32 {",
      "  heap.swap(0, heap.len()-1); let max = heap.pop().unwrap();",
      "  heapify(heap, heap.len(), 0);",
      "  max",
      "}",
    ],
    java: [
      "void heapify(int[] arr, int n, int i) {",
      "  int largest = i, l = 2*i+1, r = 2*i+2;",
      "  if (l < n && arr[l] > arr[largest]) largest = l;",
      "  if (r < n && arr[r] > arr[largest]) largest = r;",
      "  if (largest != i) { swap(arr,i,largest); heapify(arr,n,largest); }",
      "  // heap property restored",
      "}",
      "void insert(List<Integer> heap, int val) {",
      "  heap.add(val); int i = heap.size() - 1;",
      "  while (i > 0 && heap.get((i-1)/2) < heap.get(i)) {",
      "    Collections.swap(heap, i, (i-1)/2); i = (i-1)/2;",
      "  }",
      "}",
      "int extractMax(List<Integer> heap) {",
      "  Collections.swap(heap, 0, heap.size()-1); int max = heap.remove(heap.size()-1);",
      "  heapify0(heap, 0);",
      "  return max;",
      "}",
    ],
  },
} as Partial<Record<AlgoId, Snippet>>;

// activeLine values per algorithm per frame type
// Lines are 0-indexed, matching the code arrays above
export const SORT_LINES = {
  "bubble-sort": { comparing: 4, swapping: 5, sorted: 7, done: 9 },
  "selection-sort": { comparing: 5, swapping: 7, sorted: 7, done: 9 },
  "insertion-sort": { comparing: 3, swapping: 4, sorted: 6, done: 8 },
  "merge-sort": { comparing: 8, swapping: 8, sorted: 12, done: 12 },
  "quick-sort": { comparing: 5, swapping: 7, sorted: 10, done: 13, pivot: 3 },
} as Record<string, Record<string, number>>;

export const GRAPH_LINES = {
  init: 1,
  dequeue: 6,
  checkGoal: 7,
  checkNeighbor: 10,
  addVisited: 11,
  addParent: 12,
  addFrontier: 13,
  noPath: 17,
};
